test coverage

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,13 +63,26 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
-      - name: Install Docker on macOS
+        - name: Install Docker on macOS
         if: runner.os == 'macOS'
         run: |
           brew install --cask docker
           open /Applications/Docker.app
-          # Wait for Docker to start
-          while ! docker system info > /dev/null 2>&1; do sleep 1; done
+          # Wait for the Docker app to fully initialize
+          sleep 10
+          # Check if Docker is ready in a loop with a timeout
+          for i in {1..30}; do
+            if docker system info > /dev/null 2>&1; then
+              echo "Docker is ready."
+              break
+            fi
+            echo "Waiting for Docker to initialize..."
+            sleep 10
+          done
+          if [ $i -eq 30 ]; then
+            echo "Docker failed to initialize."
+            exit 1
+          fi
 
       - name: Install Docker on Windows
         if: runner.os == 'Windows'
